services:
  erp:
    build: .
    container_name: erp-app
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./data:/data
      - ./storage:/app/public
    env_file:
      - .env.production
